version: '2'
services:

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    env_file:
    - ${PWD}/.env
    stdin_open: true
    tty: true
    volumes:
    - etc:/etc/grafana
    - lib:/var/lib/grafana
    - log:/var/log/grafana
    expose:
    - "3000"
    labels:
      service: grafana
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

volumes:
  etc:
    driver: "local"
  lib:
    driver: "local"
  log:
    driver: "local"
