version: '2'
services:
  grafana:
    scale: 1
    start_on_create: true
    health_check:
      port: 3000
      interval: 60000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
